=== laurentkeil/WebTech-Challenge-1/thermostat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/thermostat" xmlns="http://www.example.org/thermostat"
	elementFormDefault="qualified">
	<xs:element name="thermostatData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dailyMeasurement" type="measurementType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="model">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" />
					</xs:complexType>
				</xs:element>
				<xs:element name="user-ID" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="measurementType">
		<xs:sequence>
			<xs:element name="date" type="xs:date" />
			<xs:element name="measurement" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="temperature">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="value" type="double" />
									<xs:element name="unit" type="xs:string" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="time-stamp" type="xs:time" />
						<xs:element name="humidity" type="xs:integer" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="double">
		<xs:sequence>
			<xs:element name="integer-part" type="xs:int" />
			<xs:element name="fraction-part" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== laurentkeil/WebTech-Challenge-1/thermostat.xml
<?xml version="1.0" encoding="UTF-8"?>
<t:thermostatData xmlns:t="http://www.example.org/thermostat"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/thermostat thermostat.xsd ">
	<t:dailyMeasurement>
		<t:date>2001-01-01</t:date>
		<t:measurement>
			<t:temperature>
				<t:value>
					<t:integer-part>10</t:integer-part>
					<t:fraction-part>20</t:fraction-part>
				</t:value>
				<t:unit>Centigrade</t:unit>
			</t:temperature>
			<t:time-stamp>12:00:00</t:time-stamp>
			<t:humidity>63</t:humidity>
		</t:measurement>
	</t:dailyMeasurement>
	<t:dailyMeasurement>
		<t:date>2001-01-01</t:date>
		<t:measurement>
		<t:temperature>
			<t:value>
				<t:integer-part>17</t:integer-part>
				<t:fraction-part>25</t:fraction-part>
			</t:value>
			<t:unit>Centigrade</t:unit>
		</t:temperature>
		<t:time-stamp>12:30:00</t:time-stamp>
		<t:humidity>73</t:humidity>
		</t:measurement>
	</t:dailyMeasurement>
	<t:dailyMeasurement>
		<t:date>2004-01-01</t:date>
		<t:measurement>
		   <t:temperature>
			<t:value>
				<t:integer-part>40</t:integer-part>
				<t:fraction-part>50</t:fraction-part>
			</t:value>
			<t:unit>Centigrade</t:unit>
		</t:temperature>
		<t:time-stamp>12:00:00</t:time-stamp>
		<t:humidity>53</t:humidity>
		</t:measurement>
	</t:dailyMeasurement>
	<t:dailyMeasurement>
		<t:date>2007-01-01</t:date>
		<t:measurement>
		<t:temperature>
			<t:value>
				<t:integer-part>30</t:integer-part>
				<t:fraction-part>10</t:fraction-part>
			</t:value>
			<t:unit>Centigrade</t:unit>
		</t:temperature>
		<t:time-stamp>12:00:00</t:time-stamp>
		<t:humidity>63</t:humidity>
		</t:measurement>
	</t:dailyMeasurement>
	<t:dailyMeasurement>
		<t:date>2007-01-01</t:date>
		<t:measurement>
			<t:temperature>
				<t:value>
					<t:integer-part>20</t:integer-part>
					<t:fraction-part>4</t:fraction-part>
				</t:value>
				<t:unit>Centigrade</t:unit>
			</t:temperature>
			<t:time-stamp>18:10:00</t:time-stamp>
			<t:humidity>73</t:humidity>
		</t:measurement>
	</t:dailyMeasurement>
	<t:dailyMeasurement>
		<t:date>2011-01-01</t:date>
		<t:measurement>
			<t:temperature>
				<t:value>
					<t:integer-part>33</t:integer-part>
					<t:fraction-part>12</t:fraction-part>
				</t:value>
				<t:unit>Centigrade</t:unit>
			</t:temperature>
			<t:time-stamp>03:00:00</t:time-stamp>
			<t:humidity>53</t:humidity>
		</t:measurement>
	</t:dailyMeasurement>
	<t:dailyMeasurement>
		<t:date>2011-01-01</t:date>
		<t:measurement>
			<t:temperature>
				<t:value>
					<t:integer-part>15</t:integer-part>
					<t:fraction-part>3</t:fraction-part>
				</t:value>
				<t:unit>Centigrade</t:unit>
			</t:temperature>
			<t:time-stamp>12:00:00</t:time-stamp>
			<t:humidity>43</t:humidity>
		</t:measurement>
	</t:dailyMeasurement>
	<t:dailyMeasurement>
		<t:date>2014-01-01</t:date>
		<t:measurement>
			<t:temperature>
				<t:value>
					<t:integer-part>40</t:integer-part>
					<t:fraction-part>50</t:fraction-part>
				</t:value>
				<t:unit>Centigrade</t:unit>
			</t:temperature>
			<t:time-stamp>12:00:00</t:time-stamp>
			<t:humidity>83</t:humidity>
		</t:measurement>
	</t:dailyMeasurement>
	<t:dailyMeasurement>
		<t:date>2014-01-01</t:date>
		<t:measurement>
			<t:temperature>
				<t:value>
					<t:integer-part>0</t:integer-part>
					<t:fraction-part>50</t:fraction-part>
				</t:value>
				<t:unit>Centigrade</t:unit>
			</t:temperature>
			<t:time-stamp>15:00:00</t:time-stamp>
			<t:humidity>83</t:humidity>
		</t:measurement>
	</t:dailyMeasurement>
	<t:dailyMeasurement>
		<t:date>2015-01-01</t:date>
		<t:measurement>
			<t:temperature>
				<t:value>
					<t:integer-part>0</t:integer-part>
					<t:fraction-part>50</t:fraction-part>
				</t:value>
				<t:unit>Centigrade</t:unit>
			</t:temperature>
			<t:time-stamp>15:00:00</t:time-stamp>
			<t:humidity>83</t:humidity>
		</t:measurement>
	</t:dailyMeasurement>
	<t:model name ="Honeywell TH"/>
	<t:user-ID>Namur-Barbi-1234</t:user-ID>
</t:thermostatData>
